version: '3.9'

services:
  web:
    build: .
    container_name: 'web'
    ports:
      - 5000:5000
    volumes:
      - ./:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    environment:
      - APP_PORT=5000
      - APP_PG_CONNECT=postgresql://postgres:postgres@postgres:5432/postgres

  postgres:
    image: postgres:13
    container_name: 'postgres'
    ports:
      - 15432:5432
    volumes:
      - dump:/usr/src/app/dump
      - postgresql:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: 'postgres'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'

volumes:
  node_modules:
  postgresql:
  dump:
